language: c
sudo: required

# language: fortran does not install gfortran!!
before_install:
    - sudo apt-get install gfortran

script:
    - make
    - cd build
    - ./hello

after_success:
    - bash <(curl -s https://codecov.io/bash)
